### 3.1.1 (관리자) 그룹 만들기
// @no-log
POST {{host_url}}/v1/admins/groups
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "{{account.API_3_1_1.name}}"
}

### 3.2.1 유저 배송 정보 조회
// @no-log
GET {{host_url}}/v1/users/summaries
Authorization: Bearer {{access_token}}

### 3.2.2 유저 상세 정보 조회
// @no-log
GET {{host_url}}/v1/users/details
Authorization: Bearer {{access_token}}

### 3.2.3 (관리자) 유저 상세 정보 조회
// @no-log
GET {{host_url}}/v1/admins/users/{{account.API_3_2_3.id}}/details?user_id
Authorization: Bearer {{access_token}}


### 3.2.4 (관리자) 유저 리스트 조회
// @no-log
GET {{host_url}}/v1/admins/users/overviews?page=1&size=10&start-date=2025.01.01&end-date=2025.12.31
Authorization: Bearer {{access_token}}

### 3.4.1 유저 정보 수정
// @no-log
PUT {{host_url}}/v1/users
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "phone_number": "{{account.API_3_4_1.phone_number}}",
    "email": "{{account.API_3_4_1.email}}",
    "address": {
      "address_name": "{{account.API_3_4_1.address.address_name}}",
      "region_1depth_name": "{{account.API_3_4_1.address.region_1depth_name}}",
      "region_2depth_name": "{{account.API_3_4_1.address.region_2depth_name}}",
      "region_3depth_name": "{{account.API_3_4_1.address.region_3depth_name}}",
      "address_detail": "{{account.API_3_4_1.address.address_detail}}",
      "latitude": {{account.API_3_4_1.address.latitude}},
      "longitude": {{account.API_3_4_1.address.longitude}}
    }
}

### 3.4.2 (관리자) 유저 정보 수정
// @no-log
PUT {{host_url}}/v1/admins/users/{{account.API_3_4_2.id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "name": "{{account.API_3_4_2.name}}",
    "phone_number": "{{account.API_3_4_2.phone_number}}",
    "memo": "{{account.API_3_4_2.memo}}"
}

### 3.4.3 (관리자) 사용자 그룹 지정
// @no-log
PUT {{host_url}}/v1/admins/groups/users
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "user_ids": ["{{account.API_3_4_3.user_ids}}"],
  "group_ids": [{{account.API_3_4_3.group_ids}}]
}
